version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "225398952196"
    REGION: "us-east-1"
    REPO_NAME: "dev/mindtrack"
    IMAGE_TAG: "latest"
    CLUSTER_NAME: "mindtrack-cluster"


phases:
  install:
    commands:
      - uname -m
      - ARCH=$(uname -m)
      - |
        if [ "$ARCH" = "x86_64" ]; then
          KUBECTL_ARCH=amd64
        elif [ "$ARCH" = "aarch64" ]; then
          KUBECTL_ARCH=arm64
        else
          exit 1
        fi
      - curl -fL https://dl.k8s.io/release/v1.29.3/bin/linux/$KUBECTL_ARCH/kubectl -o kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo Checking if repository exists...
      - |
        aws ecr describe-repositories --repository-names $REPO_NAME --region $REGION || \
        aws ecr create-repository --repository-name $REPO_NAME --region $REGION

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Deploying to $CLUSTER_NAME
      - |
        echo "Updating kubeconfig for EKS cluster..."
        aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
        NAMESPACE="dev"

        if kubectl get namespace "$NAMESPACE" >/dev/null 2>&1; then
          echo "Namespace '$NAMESPACE' already exists."
        else
          echo "Namespace '$NAMESPACE' not found. Creating it now..."
          kubectl create namespace "$NAMESPACE"
          echo "Namespace '$NAMESPACE' created."
        fi

        if kubectl get secret "ecr-creds" -n $NAMESPACE >/dev/null 2>&1; then
          echo "Secret ecr-creds already exists"
        else
          echo "Secret ecr-creds not found. Creating it now.."
          kubectl create secret docker-registry ecr-creds --docker-server=2253989521965.dkr.ecr.us-east-1.amazonaws.com --docker-username=AWS --docker-password="$(aws ecr get-login-password --region us-east-1)" -n dev
          echo "Secret ecr-creds created"
        fi
      - kubectl apply -f k8s/deployment.yaml -n dev
      - kubectl apply -f k8s/service.yaml -n dev

artifacts:
  files:
    - '**/*'
